/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gy.avro.login;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8685286913923892971L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserResponse\",\"namespace\":\"com.gy.avro.login\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"loginToken\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserResponse> ENCODER =
      new BinaryMessageEncoder<UserResponse>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserResponse> DECODER =
      new BinaryMessageDecoder<UserResponse>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<UserResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<UserResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserResponse>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this UserResponse to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a UserResponse from a ByteBuffer. */
  public static UserResponse fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence loginToken;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserResponse() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param loginToken The new value for loginToken
   */
  public UserResponse(java.lang.CharSequence name, java.lang.CharSequence loginToken) {
    this.name = name;
    this.loginToken = loginToken;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return loginToken;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: loginToken = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'loginToken' field.
   * @return The value of the 'loginToken' field.
   */
  public java.lang.CharSequence getLoginToken() {
    return loginToken;
  }

  /**
   * Sets the value of the 'loginToken' field.
   * @param value the value to set.
   */
  public void setLoginToken(java.lang.CharSequence value) {
    this.loginToken = value;
  }

  /**
   * Creates a new UserResponse RecordBuilder.
   * @return A new UserResponse RecordBuilder
   */
  public static com.gy.avro.login.UserResponse.Builder newBuilder() {
    return new com.gy.avro.login.UserResponse.Builder();
  }

  /**
   * Creates a new UserResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserResponse RecordBuilder
   */
  public static com.gy.avro.login.UserResponse.Builder newBuilder(com.gy.avro.login.UserResponse.Builder other) {
    return new com.gy.avro.login.UserResponse.Builder(other);
  }

  /**
   * Creates a new UserResponse RecordBuilder by copying an existing UserResponse instance.
   * @param other The existing instance to copy.
   * @return A new UserResponse RecordBuilder
   */
  public static com.gy.avro.login.UserResponse.Builder newBuilder(com.gy.avro.login.UserResponse other) {
    return new com.gy.avro.login.UserResponse.Builder(other);
  }

  /**
   * RecordBuilder for UserResponse instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserResponse>
    implements org.apache.avro.data.RecordBuilder<UserResponse> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence loginToken;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gy.avro.login.UserResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.loginToken)) {
        this.loginToken = data().deepCopy(fields()[1].schema(), other.loginToken);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing UserResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gy.avro.login.UserResponse other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.loginToken)) {
        this.loginToken = data().deepCopy(fields()[1].schema(), other.loginToken);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.gy.avro.login.UserResponse.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.gy.avro.login.UserResponse.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'loginToken' field.
      * @return The value.
      */
    public java.lang.CharSequence getLoginToken() {
      return loginToken;
    }

    /**
      * Sets the value of the 'loginToken' field.
      * @param value The value of 'loginToken'.
      * @return This builder.
      */
    public com.gy.avro.login.UserResponse.Builder setLoginToken(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.loginToken = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'loginToken' field has been set.
      * @return True if the 'loginToken' field has been set, false otherwise.
      */
    public boolean hasLoginToken() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'loginToken' field.
      * @return This builder.
      */
    public com.gy.avro.login.UserResponse.Builder clearLoginToken() {
      loginToken = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserResponse build() {
      try {
        UserResponse record = new UserResponse();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.loginToken = fieldSetFlags()[1] ? this.loginToken : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserResponse>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserResponse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserResponse>
    READER$ = (org.apache.avro.io.DatumReader<UserResponse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
